services:
  iduff:
    image: iduff
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aspnetapp.pfx
    volumes:
      - ./aspnetapp.pfx:/aspnetapp.pfx:ro
    ports:
      - "8080"
      - "8081"
    build:
      context: .
      dockerfile: Dockerfile
